### ISSUE TITLE
Problem with the drone code

### ISSUE THREAD

**Issue by ozzy69** [TomE8/drones#18]
Hello Tom, i was tried to use your drone's code in my drone, but my drone is a little bit different, cause my drone is jjrc h68. So, when i was run your code in my drone, appear this tk:

https://sites.google.com/site/negocindosica/Captura%20de%20tela%20de%202020-07-12%2001-44-34.png

but closed suddenly. Do you know how to fix it? Help me!

**Comment by TomE8** [comment]
Hey ozzy69,
Note that my code build and tested only for the JJRC H47 ELFIE+ drone. I suppose that your drone uses different communication protocol, therefore this code is not suit for it. I have done a long research in order to gain control over the H47 drone and I believe it wont be so easy to adjust the current project to your drone.
If you are intrested on how to conduct such research, I advice you to read this project to get some ideas:
[](https://hackaday.io/project/19680-controlling-a-jjrc-h37-elfie-quad-from-a-pc)
good luck,
Tom
